name: Android CI

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build CarControl
        run: |
          cd CarControl
          ./gradlew build --stacktrace
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for Car controller APP
        run: |
          cd CarControl
          ./gradlew test --info
  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: make gradlew available
        run: |
            cd CarControl
            chmod +x gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run instrumented tests for CarControl UI
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: Nexus 6
          api-level: 29
          arch: x86_64
          working-directory: ./CarControl
          script: ./gradlew connectedCheck
